<?php

namespace EKF_Functions\Inc\Common\EkfAcf;
use StoutLogic\AcfBuilder\FieldsBuilder as FieldsBuilder;

use EKF_Functions\Inc\Common\EkfAcf\Components;
use EKF_Functions\Inc\Common\EkfAcf\Views;

/**
 * Fired during plugin activation
 *
 * This class defines all code necessary to run during the plugin's activation.
 *
 * @link       http://example.com
 * @since      1.0.0
 *
 * @author     Your Name or Your Company
 **/




class EkfAcf {

	/**
	 * Short Description.
	 *
	 * Long Description.
	 *
	 * @since    1.0.0
	 */

  public static $json_path;


  public function __construct() {
		$this->live = $this->test_acf();
		if ($this->live) {
			acf_add_options_page(['page_title'=> __("Global Options"), 'menu_slug' => 'site-options', 'autoload' => true]);
		}
	}

	public static function test_acf() {
		if (function_exists('get_field') || class_exists(ACF)) {
			return true;
		}
	}
	public function create_fields() {
		$this->init();
		$this->add_instructions();
		$this->create_site();
		$this->create_artist();
		$this->create_release();
	}

	public  function init() {

		$this->createMainPage();
		$this->imageFocus();

	}

	public function add_instructions() {
		add_action('edit_form_after_editor', function() {
			echo '<p class="ekfacf-instructions">';
				if ('artist' === get_post_type()) {
					echo 'Add an artist description/bio. This will be used in autogenerated about sections and on the artist archive of releases.';
				} elseif ('release' == get_post_type()) {
					echo 'Add an release description. This will be used on the page as "About the release" content.';
				}
			echo '</p>';
		});
	}

	public function imageFocus() {
		$image_focus = new FieldsBuilder('Image Focal Point');
		$image_focus
			->addRange('horizontal', ['label' => "Horizontal Center", "min" => 0, "max" => 100, "step" => 1])
				->setDefaultValue(50)
			->addRange('vertical', ['label' => "Vertical Center", "min" => 0, "max" => 100, "step" => 1])
				->setDefaultValue(50)
			->setLocation('attachment', '==', 'image');
			add_action('acf/init', function() use ($image_focus) {
				acf_add_local_field_group($image_focus->build());
			});
	}

	public function createMainPage() {
		$main_page = Views\Home::create();

			add_action('acf/init', function() use ($main_page) {
				acf_add_local_field_group($main_page->build());
			});
	}



	public function create_site() {
		$options = Views\Site::create();

		add_action('acf/init', function() use ($options) {
			acf_add_local_field_group($options->build());
		});
	}
	public function create_artist() {
		$artist_details = Views\Artist::create();

		add_action('acf/init', function() use ($artist_details) {
			acf_add_local_field_group($artist_details->build());
		});
	}

	public function create_release() {
			$content = Views\Release::create();

			add_action('acf/init', function() use ($content) {
				acf_add_local_field_group($content->build());
			});

			$settings = Views\Release::settings();

			add_action('acf/init', function() use ($settings) {
				acf_add_local_field_group($settings->build());
			});

			add_filter('acf/fields/flexible_content/layout_title/key=field_release_options_content_gallery_content',function ($title, $field, $layout, $i) {
					if (get_sub_field('Title')) {
						return $title .= ': ' .get_sub_field('Title');
					} else {
						return $title;
					}
			}, 10, 4);
			add_filter('acf/fields/flexible_content/layout_title/key=field_release_options_content',function ($title, $field, $layout, $i) {

				if (get_sub_field('header')) {
					$items =get_sub_field('header')['text_content'];
					if ($items) {
						foreach ($items as $content) {
							if ($content['acf_fc_layout'] == 'Header' && $content['size'] != 'small') {
								return $title .= ': ' .  $content['Text'];
							}
						}
					}
				} elseif (get_sub_field('Content')) {
					$items =get_sub_field('Content')['text_content'];
					if ($items) {
						foreach ($items as $content) {
							if ($content['acf_fc_layout'] == 'Header' && $content['Size'] != 'small') {
								return $title .= ': ' . $content['Text'];
							}
						}
					}
				}
				// $group = get_sub_field('header')
				// if ($field)

				return $title;

			}, 10, 4);
		}

}


